"""add ggmap link

Revision ID: f4427233033e
Revises: 
Create Date: 2025-07-15 12:15:35.061090

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4427233033e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('walkInCustomerName', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('walkInCustomerPhone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bookingType', sa.String(length=20), nullable=True))
        batch_op.alter_column('customerId',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)

    with op.batch_alter_table('court_complexes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('googleMapLink', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('bankCode', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('accountNumber', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('accountName', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('court_complexes', schema=None) as batch_op:
        batch_op.drop_column('accountName')
        batch_op.drop_column('accountNumber')
        batch_op.drop_column('bankCode')
        batch_op.drop_column('googleMapLink')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('customerId',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('bookingType')
        batch_op.drop_column('walkInCustomerPhone')
        batch_op.drop_column('walkInCustomerName')

    # ### end Alembic commands ###
